name: Test Projects with Ekstazi

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Generate and Test Projects with Ekstazi
        run: |
          # Loop through the list of projects (adjust these values accordingly)
          projects=(
            "org.easyb easyb 0.7"
            "edu.vt.middleware vt-ldap 3.3.1"
          )

          for project in "${projects[@]}"; do
            IFS=' ' read -ra project_info <<< "$project"
            group_id="${project_info[0]}"
            artifact_id="${project_info[1]}"
            version="${project_info[2]}"

            # Create project
            mvn archetype:generate -DgroupId="$group_id" -DartifactId="$artifact_id" -Dversion="$version" -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false

            # Modify pom.xml - replace existing content with the desired content
            cat <<EOF > "$artifact_id/pom.xml"
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>$group_id</groupId>
  <artifactId>$artifact_id</artifactId>
  <version>$version</version>
  
  <build>
    <pluginManagement><!-- lock down plugins versions ... -->
      <!-- ... your plugins ... -->
    </pluginManagement>
  </build>

  <dependencies>
    <dependency>
      <groupId>example.group</groupId>
      <artifactId>example-artifact</artifactId>
      <version>1.0.0</version>
    </dependency>
    <!-- ... other dependencies ... -->
  </dependencies>
</project>
EOF

            # Test with Ekstazi
            cd "$artifact_id"
            mvn ekstazi:ekstazi
            cd ..
          done
